In this notebook we will use another data

In [14]:
import numpy as np
import pandas as pd

In [15]:
df=pd.read_csv('results.csv')

In [16]:
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [7]:
df.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49500,2026-07-07,Switzerland,Colombia,0.0,0.0,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49502,2026-07-10,Spain,Belgium,NaN,NaN,FIFA World Cup,Inglewood,United States,True
49503,2026-07-11,Norway,England,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49504,2026-07-11,Argentina,Switzerland,NaN,NaN,FIFA World Cup,Kansas City,United States,True

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49505 entries, 0 to 49504
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        49505 non-null  object
 1   home_team   49505 non-null  object
 2   away_team   49505 non-null  object
 3   home_score  49501 non-null  float64
 4   away_score  49501 non-null  float64
 5   tournament  49505 non-null  object
 6   city        49505 non-null  object
 7   country     49505 non-null  object
 8   neutral     49505 non-null  bool
dtypes: bool(1), float64(2), object(6)
memory usage: 3.1+ MB

In [18]:
df.describe()

         home_score    away_score
count  49501.000000  49501.000000
mean       1.757197      1.181936
std        1.773821      1.401655
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max       31.000000     21.000000

we see a max goal scored is 31 and 21 which is high unusal so we will remove it

In [11]:
import matplotlib.pyplot as plt
plt.hist(df[home_score'],bin=1)

false