<h1>In this dataset we will only use goalscores.csv </h1>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df_sa=pd.read_csv('goalscorers.csv')
df_e=pd.read_csv('results.csv')

now we view the data

In [ ]:
df_sa.head()

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

In [ ]:
df_e.tail()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49500,2026-07-07,Switzerland,Colombia,0.0,0.0,FIFA World Cup,Vancouver,Canada,True
49501,2026-07-09,France,Morocco,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49502,2026-07-10,Spain,Belgium,NaN,NaN,FIFA World Cup,Inglewood,United States,True
49503,2026-07-11,Norway,England,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49504,2026-07-11,Argentina,Switzerland,NaN,NaN,FIFA World Cup,Kansas City,United States,True

In [ ]:
df_sa.shape

(47886, 8)

In [ ]:
df_e.shape

(49505, 9)

After a brief review we found that after a certain date the matches in both data set are same so we will use both data sets

Futher the data set goalscores.csv contains the goal of each matches as a seperate columns . To clarify it in match of argentina vs egpty(on july 7) the score was 3-2(in favour of argentina ) so it display 5 seperate columns indicating goal score and minute at which goal is being score

Now we will be converting the event based to match based

In [ ]:
df_sa['is_home_goal'] = df_sa['team'] == df_sa['home_team']
df_sa['is_away_goal'] = df_sa['team'] == df_sa['away_team']

# 3. Group by the unique match traits and sum up the goals
cleaned_matches = df_sa.groupby(['date', 'home_team', 'away_team']).agg(
    home_score=('is_home_goal', 'sum'),
    away_score=('is_away_goal', 'sum')
).reset_index()

cleaned_matches.to_csv('cleaned_match_results.csv', index=False)

# Let's see the result
print(cleaned_matches.head())

         date  home_team away_team  home_score  away_score
0  1916-07-02      Chile   Uruguay           0           4
1  1916-07-06  Argentina     Chile           6           1
2  1916-07-08     Brazil     Chile           1           1
3  1916-07-10  Argentina    Brazil           1           1
4  1916-07-12     Brazil   Uruguay           1           2

lets overview the win ratio of the argentina and swizterland

In [ ]:
df=pd.read_csv('cleaned_match_results.csv')

In [ ]:
df.head()

         date  home_team away_team  home_score  away_score
0  1916-07-02      Chile   Uruguay           0           4
1  1916-07-06  Argentina     Chile           6           1
2  1916-07-08     Brazil     Chile           1           1
3  1916-07-10  Argentina    Brazil           1           1
4  1916-07-12     Brazil   Uruguay           1           2

In [ ]:
total_arg_game = df[(df['home_team'] == 'Argentina') | (df['away_team'] == 'Argentina')].shape[0]

print(f"Total Argentina games: {total_arg_game}")

Total Argentina games: 453

In [ ]:

arg_home_win = (df['home_team'] == 'Argentina') & (df['home_score'] > df['away_score'])

arg_away_win = (df['away_team'] == 'Argentina') & (df['away_score'] > df['home_score'])

total_arg_win_game = df[arg_home_win | arg_away_win].shape[0]

print(f"Total Argentina wins: {total_arg_win_game}")

Total Argentina wins: 291

In [ ]:
win_ratio_arg=(total_arg_win_game/total_arg_game)*100
print(f"the win ratio for argentina is {win_ratio_arg}")

the win ratio for argentina is 64.23841059602648

Feature Engineering

In [ ]:
df.shape

(15532, 5)

In [ ]:
fifa_ranking=['Argentina', 'Spain', 'France', 'England', 'Portugal', 'Brazil',
              'Morocco', 'Netherlands', 'Belgium', 'Germany', 'Croatia', 'Italy',
              'Colombia', 'Mexico', 'Senegal', 'Uruguay', 'USA', 'Japan', 'Switzerland',
              'Iran', 'Denmark', 'Türkiye', 'Ecuador', 'Austria', 'South Korea', 'Nigeria',
              'Australia', 'Algeria', 'Egypt', 'Canada', 'Norway', 'Ukraine', "Côte d'Ivoire",
              'Panama', 'Russia', 'Poland', 'Wales', 'Sweden', 'Hungary', 'Czechia', 'Paraguay', 'Scotland',
              'Serbia', 'Cameroon', 'Tunisia', 'DR Congo', 'Slovakia', 'Greece', 'Venezuela', 'Uzbekistan',
              'Chile', 'Peru', 'Costa Rica', 'Romania', 'Mali', 'Qatar', 'Iraq', 'Ireland',
              'Slovenia', 'South Africa',
              'Saudi Arabia', 'Burkina Faso', 'Jordan', 'Bosnia & Herzegovina', 'Honduras', 'Albania', 'Cape Verde', 'United Arab Emirates', 'North Macedonia', 'Northern Ireland']

now we will add three columns the home team ranking , away team ranking and difference

In [ ]:
ranking_dict = {team.title(): idx + 1 for idx, team in enumerate(fifa_ranking)}

In [ ]:
ranking_dict

{'Argentina': 1,
 'Spain': 2,
 'France': 3,
 'England': 4,
 'Portugal': 5,
 'Brazil': 6,
 'Morocco': 7,
 'Netherlands': 8,
 'Belgium': 9,
 'Germany': 10,
 'Croatia': 11,
 'Italy': 12,
 'Colombia': 13,
 'Mexico': 14,
 'Senegal': 15,
 'Uruguay': 16,
 'Usa': 17,
 'Japan': 18,
 'Switzerland': 19,
 'Iran': 20,
 'Denmark': 21,
 'Türkiye': 22,
 'Ecuador': 23,
 'Austria': 24,
 'South Korea': 25,
 'Nigeria': 26,
 'Australia': 27,
 'Algeria': 28,
 'Egypt': 29,
 'Canada': 30,
 'Norway': 31,
 'Ukraine': 32,
 "Côte D'Ivoire": 33,
 'Panama': 34,
 'Russia': 35,
 'Poland': 36,
 'Wales': 37,
 'Sweden': 38,
 'Hungary': 39,
 'Czechia': 40,
 'Paraguay': 41,
 'Scotland': 42,
 'Serbia': 43,
 'Cameroon': 44,
 'Tunisia': 45,
 'Dr Congo': 46,
 'Slovakia': 47,
 'Greece': 48,
 'Venezuela': 49,
 'Uzbekistan': 50,
 'Chile': 51,
 'Peru': 52,
 'Costa Rica': 53,
 'Romania': 54,
 'Mali': 55,
 'Qatar': 56,
 'Iraq': 57,
 'Ireland': 58,
 'Slovenia': 59,
 'South Africa': 60,
 'Saudi Arabia': 61,
 'Burkina Faso': 62,
 'Jordan': 63,
 'Bosnia & Herzegovina': 64,
 'Honduras': 65,
 'Albania': 66,
 'Cape Verde': 67,
 'United Arab Emirates': 68,
 'North Macedonia': 69,
 'Northern Ireland': 70}

In [ ]:
df['home_team_ranking']=df['home_team'].str.title().map(ranking_dict)

In [ ]:
df['away_team_ranking']=df['away_team'].str.title().map(ranking_dict)

In [ ]:
df['home_team_ranking']=df['home_team_ranking'].fillna(200).astype(int)
df['away_team_ranking']=df['away_team_ranking'].fillna(200).astype(int)

now adding the difference columns

In [ ]:
df['rank_diff']=df['home_team_ranking']-df['away_team_ranking']

In [ ]:
df.head()

,date,home_team,away_team,home_score,away_score,home_team_ranking,away_team_ranking,rank_diff
0,1916-07-02,Chile,Uruguay,0,4,51,16,35
1,1916-07-06,Argentina,Chile,6,1,1,51,-50
2,1916-07-08,Brazil,Chile,1,1,6,51,-45
3,1916-07-10,Argentina,Brazil,1,1,1,6,-5
4,1916-07-12,Brazil,Uruguay,1,2,6,16,-10

now we will take the ratio of goal score and goal conceded for it we will take the data from only 3 year(wc qualifier)

In [ ]:
df['date']=pd.to_datetime(df['date'])

In [ ]:
indices = np.where(df['date'] > pd.to_datetime('2023-01-10'))

In [ ]:
indices

(array([13935, 13936, 13937, ..., 15529, 15530, 15531]),)

In [ ]:
recent_df=df[df.index>13000].copy()

In [ ]:
recent_df

,date,home_team,away_team,home_score,away_score,home_team_ranking,away_team_ranking,rank_diff
13001,2021-03-31,Liechtenstein,Iceland,1,4,200,200,0
13002,2021-03-31,Lithuania,Italy,0,2,200,12,188
13003,2021-03-31,Moldova,Israel,1,4,200,200,0
13004,2021-03-31,San Marino,Albania,0,2,200,66,134
13005,2021-03-31,Scotland,Faroe Islands,4,0,42,200,-158
...,...,...,...,...,...,...,...,...
15527,2026-07-05,Brazil,Norway,1,2,6,31,-25
15528,2026-07-05,Mexico,England,2,3,14,4,10
15529,2026-07-06,Portugal,Spain,0,1,5,2,3
15530,2026-07-06,United States,Belgium,1,4,200,9,191
15531,2026-07-07,Argentina,Egypt,3,2,1,29,-28

In [ ]:
home_stat=recent_df.groupby('home_team').agg(
     home_goals_scored=('home_score', 'sum'),
    home_goals_conceded=('away_score', 'sum'),
    home_matches=('home_score', 'count')
)

In [ ]:
away_stat=recent_df.groupby('away_team').agg(
    away_goals_scored=('away_score', 'sum'),
    away_goals_conceded=('home_score', 'sum'),
    away_matches=('away_score', 'count')
)

In [ ]:
home_stat

             home_goals_scored  home_goals_conceded  home_matches
home_team
Afghanistan                  2                    6             3
Albania                     21                   10            15
Algeria                     45                   20            18
Andorra                      8                   28            15
Angola                      17                   10            11
...                        ...                  ...           ...
Vietnam                     10                   12            10
Wales                       43                   32            23
Yemen                        5                    8             5
Zambia                      10                   11             9
Zimbabwe                     8                   12             8

[208 rows x 3 columns]

In [ ]:
away_stat

                away_goals_scored  away_goals_conceded  away_matches
away_team
Afghanistan                     6                   12             6
Albania                        21                   28            20
Algeria                        23                   14            13
American Samoa                  0                    2             1
Andorra                        11                   35            17
...                           ...                  ...           ...
Vietnam                        16                   29            12
Wales                          27                   25            19
Yemen                           4                    9             5
Zambia                          8                   15             9
Zimbabwe                        6                   17            11

[210 rows x 3 columns]

In [ ]:
team_stat=home_stat.join(away_stat,how='outer').fillna(0)

In [ ]:
team_stat

,home_goals_scored,home_goals_conceded,home_matches,away_goals_scored,away_goals_conceded,away_matches
Afghanistan,2.0,6.0,3.0,6.0,12.0,6.0
Albania,21.0,10.0,15.0,21.0,28.0,20.0
Algeria,45.0,20.0,18.0,23.0,14.0,13.0
American Samoa,0.0,0.0,0.0,0.0,2.0,1.0
Andorra,8.0,28.0,15.0,11.0,35.0,17.0
...,...,...,...,...,...,...
Vietnam,10.0,12.0,10.0,16.0,29.0,12.0
Wales,43.0,32.0,23.0,27.0,25.0,19.0
Yemen,5.0,8.0,5.0,4.0,9.0,5.0
Zambia,10.0,11.0,9.0,8.0,15.0,9.0
Zimbabwe,8.0,12.0,8.0,6.0,17.0,11.0

In [ ]:
team_stat['total_matches'] = team_stat['home_matches'] + team_stat['away_matches']
team_stat['goals_scored_ratio'] = (team_stat['home_goals_scored'] + team_stat['away_goals_scored']) / team_stat['total_matches']
team_stat['goals_conceded_ratio'] = (team_stat['home_goals_conceded'] + team_stat['away_goals_conceded']) / team_stat['total_matches']
scored_dict=team_stat['goals_scored_ratio'].to_dict()
conceded_dict=team_stat['goals_conceded_ratio'].to_dict()

In [ ]:
df['home_team_goals_scored_ratio'] = df['home_team'].map(scored_dict)
df['home_team_goals_conceded_ratio'] = df['home_team'].map(conceded_dict)

df['away_team_goals_scored_ratio'] = df['away_team'].map(scored_dict)
df['away_team_goals_conceded_ratio'] = df['away_team'].map(conceded_dict)

df[['home_team_goals_scored_ratio', 'home_team_goals_conceded_ratio',
    'away_team_goals_scored_ratio', 'away_team_goals_conceded_ratio']] = df[[
    'home_team_goals_scored_ratio', 'home_team_goals_conceded_ratio',
    'away_team_goals_scored_ratio', 'away_team_goals_conceded_ratio']].fillna(0)

In [ ]:
df.head()

,date,home_team,away_team,home_score,away_score,home_team_ranking,away_team_ranking,rank_diff,home_team_goals_scored_ratio,home_team_goals_conceded_ratio,away_team_goals_scored_ratio,away_team_goals_conceded_ratio
0,1916-07-02,Chile,Uruguay,0,4,51,16,35,0.781250,1.656250,1.500000,1.026316
1,1916-07-06,Argentina,Chile,6,1,1,51,-50,1.909091,0.600000,0.781250,1.656250
2,1916-07-08,Brazil,Chile,1,1,6,51,-45,1.851064,0.680851,0.781250,1.656250
3,1916-07-10,Argentina,Brazil,1,1,1,6,-5,1.909091,0.600000,1.851064,0.680851
4,1916-07-12,Brazil,Uruguay,1,2,6,16,-10,1.851064,0.680851,1.500000,1.026316

now we will make a target label

In [ ]:
df['target']=(df['home_score'] > df['away_score']).astype(int)

In [ ]:
df['target']

0        0
1        1
2        0
3        0
4        0
        ..
15527    0
15528    0
15529    0
15530    0
15531    1
Name: target, Length: 15532, dtype: int64

In [ ]:
df.head()

,date,home_team,away_team,home_score,away_score,home_team_ranking,away_team_ranking,rank_diff,home_team_goals_scored_ratio,home_team_goals_conceded_ratio,away_team_goals_scored_ratio,away_team_goals_conceded_ratio,target
0,1916-07-02,Chile,Uruguay,0,4,51,16,35,0.781250,1.656250,1.500000,1.026316,0
1,1916-07-06,Argentina,Chile,6,1,1,51,-50,1.909091,0.600000,0.781250,1.656250,1
2,1916-07-08,Brazil,Chile,1,1,6,51,-45,1.851064,0.680851,0.781250,1.656250,0
3,1916-07-10,Argentina,Brazil,1,1,1,6,-5,1.909091,0.600000,1.851064,0.680851,0
4,1916-07-12,Brazil,Uruguay,1,2,6,16,-10,1.851064,0.680851,1.500000,1.026316,0

Now removing the text based features

In [ ]:
df=df.drop(columns=['date',	'home_team', 'away_team','home_score','away_score'])

In [ ]:
df.shape

(15532, 8)

In [ ]:
df.isnull().sum()

home_team_ranking                 0
away_team_ranking                 0
rank_diff                         0
home_team_goals_scored_ratio      0
home_team_goals_conceded_ratio    0
away_team_goals_scored_ratio      0
away_team_goals_conceded_ratio    0
target                            0
dtype: int64

we will go into model building.<br>
first we will split the data

In [ ]:
y=df['target']
df=df.drop(columns=['target'])
X=df

In [ ]:
X.head(n=7)

,home_team_ranking,away_team_ranking,rank_diff,home_team_goals_scored_ratio,home_team_goals_conceded_ratio,away_team_goals_scored_ratio,away_team_goals_conceded_ratio
0,51,16,35,0.781250,1.656250,1.500000,1.026316
1,1,51,-50,1.909091,0.600000,0.781250,1.656250
2,6,51,-45,1.851064,0.680851,0.781250,1.656250
3,1,6,-5,1.909091,0.600000,1.851064,0.680851
4,6,16,-10,1.851064,0.680851,1.500000,1.026316
5,16,51,-35,1.500000,1.026316,0.781250,1.656250
6,1,6,-5,1.909091,0.600000,1.851064,0.680851

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
model=RandomForestClassifier()

In [ ]:
param_grid={
    'criterion': ['gini', 'entropy'],
    'max_depth':[5,7,8,9],
    'min_samples_split':[9,11,13,15],
    'max_features':['sqrt','log2'],
    'min_samples_leaf':[1,3,5,7],
}

In [ ]:
random=RandomizedSearchCV(
    estimator=model,
    param_distributions=param_grid,
    n_jobs=-1,
    cv=5,
    scoring='accuracy',
    n_iter=100,
    random_state=42
)

In [ ]:
random.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [5, 7, 8, 9],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 3, 5, 7],
                                        'min_samples_split': [9, 11, 13, 15]},
                   random_state=42, scoring='accuracy')

In [ ]:
best_model = random.best_estimator_

In [ ]:
best_model

RandomForestClassifier(criterion='entropy', max_depth=8, max_features='log2',
                       min_samples_leaf=7, min_samples_split=13)

In [ ]:
y_pred = best_model.predict(X_test)

now lets have some galace to metrics

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import cross_val_score

In [ ]:
print("Best Parameters:", random.best_params_)
print("Test Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
cv_score = cross_val_score(best_model, X, y, cv=5)
print("\nMean CV Accuracy:", cv_score.mean())

Best Parameters: {'min_samples_split': 13, 'min_samples_leaf': 7, 'max_features': 'log2', 'max_depth': 8, 'criterion': 'entropy'}
Test Accuracy: 0.7161248793047956

Classification Report:
               precision    recall  f1-score   support

           0       0.71      0.67      0.69      1441
           1       0.72      0.76      0.74      1666

    accuracy                           0.72      3107
   macro avg       0.71      0.71      0.71      3107
weighted avg       0.72      0.72      0.72      3107


Mean CV Accuracy: 0.7078337949059215

In [ ]:
import joblib as jb
jb.dump(best_model, "rf_model.pkl")

['rf_model.pkl']